# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'Bolts-Swift-Utils' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'Bolts-Swift'
  pod 'Alamofire', '~> 3.4'
  pod 'EVReflection'
  pod 'Version', :git => 'https://github.com/voxuanthinh/Version-iOS'
  pod 'SwiftyUserDefaults'

  # Pods for Bolts-Swift-Utils

  target 'Bolts-Swift-UtilsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Bolts-Swift'
    pod 'EVReflection'
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyUserDefaults'
  end

  target 'Bolts-Swift-UtilsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
